apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: tortuga-planke
  namespace: default
  labels:
    team: pensjonsamhandling
spec:
  image: {{ image }}
  port: 8080
  ingresses:
    - https://tortuga-planke.nais.adeo.no
  liveness:
    path: isAlive
  readiness:
    path: isReady
  replicas:
    min: 1
    max: 1
  vault:
    enabled: true